// Define an array to store the schedule data

exports.vehicleData = [
  {
    id: 1,
    schedules: [
      {
        startDate: "2023-07-09",
        endDate: "2023-07-09",
        startTime: "09:00 AM",
        endTime: "11:00 AM",
        driver: "Wisdom Ademola",
        client: "Clinton",
        clients_company: "British Petroleum",
        service: "Full Dental Rental",
        pick_up_location: "Zuma Close, Osborne Phase 1 Estate, Ikoyi",
        drop_off_location: "Same as Pickup Location",
        createdBy: "Adekunle Ajasin",
      },
      {
        startDate: "2023-07-10",
        endDate: "2023-07-10",
        startTime: "02:00 PM",
        endTime: "04:00 PM",
        driver: "James David",
        client: "Charles",
        clients_company: "Dangote Ltd",
        service: "Full Dental Rental",
        pick_up_location: "Zuma Close, Osborne Phase 1 Estate, Ikoyi",
        drop_off_location: "Same as Pickup Location",
        createdBy: "Adekunle Ajasin",
      },
      {
        startDate: "2023-07-12",
        endDate: "2023-07-15",
        startTime: "11:00 AM",
        endTime: "01:00 PM",
        driver: "James David",
        client: "Charles",
        clients_company: "Dangote Ltd",
        service: "Full Dental Rental",
        pick_up_location: "Zuma Close, Osborne Phase 1 Estate, Ikoyi",
        drop_off_location: "Same as Pickup Location",
        createdBy: "Adekunle Ajasin",
      },
      {
        startDate: "2023-08-20",
        endDate: "2023-08-20",
        startTime: "11:00 AM",
        endTime: "01:00 PM",
        driver: "James David",
        client: "Charles",
        clients_company: "Dangote Ltd",
        service: "Full Dental Rental",
        pick_up_location: "Zuma Close, Osborne Phase 1 Estate, Ikoyi",
        drop_off_location: "Same as Pickup Location",
        createdBy: "Adekunle Ajasin",
      },
      {
        startDate: "2023-08-22",
        endDate: "2023-08-22",
        startTime: "11:00 AM",
        endTime: "01:00 PM",
        driver: "James David",
        client: "Charles",
        clients_company: "Dangote Ltd",
        service: "Full Dental Rental",
        pick_up_location: "Zuma Close, Osborne Phase 1 Estate, Ikoyi",
        drop_off_location: "Same as Pickup Location",
        createdBy: "Adekunle Ajasin",
      },
    ],
    status: true,
    size: "Full Size SUV",
    brand: "Lexus GLS 500",
  },
  {
    id: 2,
    schedules: [
      {
        startDate: "2023-07-10",
        endDate: "2023-07-12",
        startTime: "09:00 AM",
        endTime: "12:00 PM",
        driver: "James David",
        client: "Charles",
        clients_company: "Dangote Ltd",
        service: "Full Dental Rental",
        pick_up_location: "Zuma Close, Osborne Phase 1 Estate, Ikoyi",
        drop_off_location: "Same as Pickup Location",
        createdBy: "Adekunle Ajasin",
      },
      {
        startDate: "2023-07-14",
        endDate: "2023-07-15",
        startTime: "01:00 PM",
        endTime: "03:00 PM",
        driver: "James David",
        client: "Charles",
        clients_company: "Dangote Ltd",
        service: "Full Dental Rental",
        pick_up_location: "Zuma Close, Osborne Phase 1 Estate, Ikoyi",
        drop_off_location: "Same as Pickup Location",
        createdBy: "Adekunle Ajasin",
      },
    ],
    status: false,
    size: "Full Size SUV",
    brand: "Lexus GLS 450",
  },
  {
    id: 3,
    schedules: [
      {
        startDate: "2023-07-09",
        endDate: "2023-07-13",
        startTime: "10:00 AM",
        endTime: "02:00 PM",
        driver: "James David",
        client: "Charles",
        clients_company: "Dangote Ltd",
        service: "Full Dental Rental",
        pick_up_location: "Zuma Close, Osborne Phase 1 Estate, Ikoyi",
        drop_off_location: "Same as Pickup Location",
        createdBy: "Adekunle Ajasin",
      },
    ],
    status: false,
    size: "Mid Size Sedan",
    brand: "Toyota Camry",
  },
];
